### ISSUE TITLE
https://github.com/Cerbrus

### ISSUE THREAD

**Issue by Cerbrus** [mikedidthis/avatars#15]
I'd love an a standard icon :D

**Comment by Cerbrus** [comment]
Oh I saw some activity here :D Are you working on these again?

**Comment by mikedidthis** [comment]
Yes sir! Should be a bunch added in the next few days.

**Comment by mikedidthis** [comment]
![Cerbrus](https://raw.githubusercontent.com/mikedidthis/avatars/master/assets/Cerbrus.png "Cerbrus")

Enjoy!
