### ISSUE TITLE
https://github.com/sippylabs

### ISSUE THREAD

**Issue by sippylabs** [mikedidthis/avatars#16]
Standard and Christmas! CHRISTMAS CRAB!

If it could follow the crab theme, that'd be sexual.

http://i.stack.imgur.com/BJHcW.jpg

**Comment by mikedidthis** [comment]
![Sippy](https://raw.githubusercontent.com/mikedidthis/avatars/master/assets/sippylabs.png "Sippy")

🐟

**Comment by mikedidthis** [comment]
![sippy-circle](https://user-images.githubusercontent.com/910412/27203170-82e2591c-521c-11e7-983a-190e83c74dfa.png)

For use in circular based avatars (twitter / discord / etc)
