### ISSUE TITLE
https://github.com/easwee

### ISSUE THREAD

**Issue by easwee** [mikedidthis/avatars#19]
Standard: Do something related to ducks.
Christmass: Do something related to ducks with hats.

**Comment by mikedidthis** [comment]
![Easwee](https://raw.githubusercontent.com/mikedidthis/avatars/master/assets/easwee.png "Easwee")

Quack quack!

**Comment by mikedidthis** [comment]
Reopening to remind myself to fix the wings.

**Comment by mikedidthis** [comment]
![Easwee](https://raw.githubusercontent.com/mikedidthis/avatars/master/assets/easwee.png "Easwee")

Quack quack!
